### ISSUE TITLE
Error after HA start

### ISSUE THREAD

**Issue by panoskpv** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Vacuum-Map-Camera#6]
I have the below error after HA start and although a camera entity is created, there are no data even after the first start.

    Error adding entities for domain camera with platform xiaomi_vacuum_map
    Error while setting up xiaomi_vacuum_map platform for camera

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in _async_write_ha_state
    extra_state_attributes = self.extra_state_attributes
  File "/config/custom_components/xiaomi_vacuum_map/camera.py", line 76, in extra_state_attributes
    "vacuum_status": self.hass.states.get(self._vacuum_entity).state
AttributeError: 'NoneType' object has no attribute 'state'

I just want to use your great HA card with a valetudo installed roborock v1. Thank you.

**Comment by PiotrMachowski** [comment]
Have you used this integration before or is it a first setup?

**Comment by panoskpv** [comment]
Thank you for the swift response. I have manually added it in HA few months ago and re-installed it today via HACS. Files in relevant folder (camera.py etc) are the newest ones

**Comment by PiotrMachowski** [comment]
Ok, so it was working before?

**Comment by panoskpv** [comment]
No. But I think I had problems with SSH to the vacuum. But I don't remember errors in logs. Any idea. Please note that I have HA os in case this changes anything

**Comment by PiotrMachowski** [comment]
Well, to be honest I don't think this custom component is a good way to get a map from your vacuum... [I can't believe it's not Valetudo](https://github.com/Hypfer/ICantBelieveItsNotValetudo) is probably a better choice

**Comment by panoskpv** [comment]
The problem is the calibration. In this model map is regenerated every time vacuum starts and the rotation of the map is not the same.

**Comment by PiotrMachowski** [comment]
Ok, have you provided a correct vacuum entity id?

**Comment by panoskpv** [comment]
I tried both valetudo and xiaomi miio intities with the same result

**Comment by PiotrMachowski** [comment]
Ok, I will have to try setting up this integration again. I haven't used it for ages

**Comment by panoskpv** [comment]
Thank you for the support
